# Generated by Django 2.1.7 on 2019-04-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('directed_by', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='movie_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('release_date', models.DateField()),
                ('censor_rating', models.CharField(max_length=10)),
                ('image_source', models.URLField()),
                ('synopsis', models.CharField(max_length=1000)),
                ('trailer_link', models.URLField()),
                ('time_duration', models.CharField(max_length=10)),
                ('likes', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AddIndex(
            model_name='movies',
            index=models.Index(fields=['title'], name='movies_movi_title_4beb4b_idx'),
        ),
    ]
