# Generated by Django 2.1.7 on 2019-04-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast_crew',
            name='cast',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cast_crew',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cast_crew',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
