# Generated by Django 2.1.7 on 2019-04-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190404_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='ratestatus',
            field=models.BooleanField(default=False),
        ),
    ]
